### ISSUE TITLE
How to fix deprecation warning: "The format Fog::CDN::AWS is deprecated"

### ISSUE THREAD

**Issue by jaredbeck** [fog/fog-aws#466]
Hi, I'd like to help fix this warning:

```
be rake -T > /dev/null
[fog][DEPRECATION] Unable to load Fog::AWS::CDN
[fog][DEPRECATION] The format Fog::CDN::AWS is deprecated
[fog][DEPRECATION] Unable to load Fog::AWS::Compute
[fog][DEPRECATION] The format Fog::Compute::AWS is deprecated
[fog][DEPRECATION] Unable to load Fog::AWS::DNS
[fog][DEPRECATION] The format Fog::DNS::AWS is deprecated
[fog][DEPRECATION] Unable to load Fog::AWS::Storage
[fog][DEPRECATION] The format Fog::Storage::AWS is deprecated
```

Do we need to eg. `mv lib/fog lib/aws`? How can I help?

See also https://github.com/fog/fog-core/pull/241

```bash
grep fog Gemfile
gem 'fog-aws'

bundle | grep fog
Using fog-core 2.1.2
Using fog-json 1.2.0
Using fog-xml 0.1.3
Using fog-aws 3.0.0
```

**Comment by Jabernathy88** [comment]
Me too.

**Comment by plribeiro3000** [comment]
You will need to change the convention from `Fog::CDN::AWS` to `Fog::AWS::CDN`.

The issue is that there is no convention among the providers so we have both ways defined here and there.

So we are deprecating the first one in favor of the second one. That should allow us to have the same implementation in all providers.

**Comment by jaredbeck** [comment]
> You will need to change the convention from Fog::CDN::AWS to Fog::AWS::CDN.

Is this something you think I can tackle? If so, I'll attempt a PR. Do you want to try to define both, or are you willing to make a breaking change (ie. release new major version)?

**Comment by plribeiro3000** [comment]
It will have to be a breaking change so a new major version will be
released.

I believe you can tackle it. It just a change in the name. =)


Em qua, 5 de set de 2018 19:27, Jared Beck <notifications@github.com>
escreveu:

**Comment by geemus** [comment]
It might be fine to have both? I think the issue at hand here is that, by default, we require the deprecated version. I think we could probably do this?

1. Change to use the new name for the class.
2. Change existing requires to use this new name.
3. Add a new class that just aliases (and will raise the warning if anybody includes directly).

I think that way we could perhaps avoid the requirement of a major version bump.

@plribeiro3000 what do you think?

@jaredbeck you can definitely go for it, we are here to support you.

**Comment by jsantos** [comment]
I'm mostly using fog-aws to interact with S3, so I also see a lot of these warnings:

`[fog][DEPRECATION] Unable to load Fog::AWS::Storage
[fog][DEPRECATION] The format Fog::Storage::AWS is deprecated`

**Comment by geemus** [comment]
@jsantos thanks, I believe there is some work-in-progress to fix this. So apologies for the noise in the mean time, hopefully we will get it all resolved soon.

**Comment by jsantos** [comment]
@geemus No rush at all, just noticed it and it hasn't been mentioned yet. I'll run a few tests and update here in case there are any other warnings.

**Comment by jaredbeck** [comment]
> .. I believe there is some work-in-progress to fix this ..

Correct. We're waiting for https://github.com/fog/fog-aws/pull/467 to be merged (it renames CDN::AWS to AWS::CDN). Once the renaming procedure is so confirmed, I will tackle other constants, probably one at a time.

**Comment by jsantos** [comment]
@jaredbeck Just for context, few other constants that will probably need renaming:

```
[fog][DEPRECATION] Unable to load Fog::AWS::Compute
[fog][DEPRECATION] The format Fog::Compute::AWS is deprecated
[fog][DEPRECATION] Unable to load Fog::AWS::DNS
[fog][DEPRECATION] The format Fog::DNS::AWS is deprecated
```

I believe when you guys are done with the first one I can submit pull requests for the others.

**Comment by DrLuthor** [comment]
Hi,
it seems I'm in the same case as @jsantos with the same warnings.

**Comment by sue445** [comment]
I fixed all other warnings at #468, #469 and #470

**Comment by agibralter** [comment]
I just updated it and I'm still seeing:


![image](https://user-images.githubusercontent.com/1079/45649326-fef40380-ba98-11e8-942c-980c13b77427.png)

```
$ rspec spec/models/user_spec.rb
[fog][DEPRECATION] Unable to load Fog::AWS::CDN
[fog][DEPRECATION] The format Fog::CDN::AWS is deprecated
...
```

**Comment by geemus** [comment]
Thanks for the update. I think maybe we missed that one, though I think we now have the others.

**Comment by stevenharman** [comment]
@agibralter @geemus looks like https://github.com/fog/fog-aws/pull/467 wasn't merged and so isn't included in 3.2.0.

**Comment by geemus** [comment]
@stevenharman oops, right you are. Just merged and released 3.3.0, sorry for the oversight.
